# Generated by Django 3.0.5 on 2020-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200612_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='strategy',
            field=models.CharField(choices=[('doc', 'Document (CAL)')], max_length=64),
        ),
    ]
