# Generated by Django 3.0.5 on 2022-06-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_max_number_of_judgments_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='show_debugging_content',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
