# Generated by Django 3.0.5 on 2024-07-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_session_show_debugging_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_activity_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
