# Generated by Django 3.0.5 on 2020-10-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201010_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='strategy',
            field=models.CharField(choices=[('doc', 'Document (CAL)'), ('doc_scal', 'Document (S-CAL)')], max_length=64),
        ),
    ]
