# Generated by Django 3.0.5 on 2020-11-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201030_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='strategy',
            field=models.CharField(choices=[('doc', 'Document (CAL)'), ('doc_scal', 'Document (DS)')], max_length=64),
        ),
    ]
