# Generated by Django 3.0.5 on 2024-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241113_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
