# Generated by Django 3.0.5 on 2024-12-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_session_session_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_data', models.TextField(blank=True, null=True)),
                ('form_type', models.CharField(choices=[('pre', 'Pre-Task questionnaire'), ('post', 'Post-Task questionnaire'), ('final', 'Post-Experiment questionnaire')], max_length=64)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
