# Generated by Django 3.0.5 on 2024-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_experimentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentform',
            name='form_type',
            field=models.CharField(max_length=64),
        ),
    ]
