# Generated by Django 3.0.5 on 2024-12-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20241216_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_time',
            field=models.IntegerField(blank=True, help_text='Max time in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='experimentform',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_forms', to='core.Session'),
        ),
    ]
