# Generated by Django 3.0.5 on 2025-01-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20241217_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
