# Generated by Django 3.0.5 on 2024-10-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241011_1316'),
        ('judgment', '0009_debuggingjudgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='core.Session'),
        ),
    ]
