# Generated by Django 3.0.5 on 2024-08-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_logevent'),
        ('judgment', '0010_auto_20240712_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session'),
        ),
    ]
