# Generated by Django 3.0.5 on 2020-12-12 23:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrel',
            name='qrel_file',
        ),
        migrations.AddField(
            model_name='qrel',
            name='qrel',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='qrel',
            name='qrel_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
